package com.example.sms_mui_compose.ui.theme.activity.activity

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.activity.enableEdgeToEdge
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Scaffold
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.tooling.preview.Preview
import com.example.sms_mui_compose.ui.theme.activity.QuestionType
import com.example.sms_mui_compose.ui.theme.activity.ui.theme.SmsmuicomposeTheme
import kotlinx.coroutines.delay
import java.io.File

class AddSurveyActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        enableEdgeToEdge()
        setContent {
            SmsmuicomposeTheme {
                Scaffold(modifier = Modifier.fillMaxSize(), topBar = { TopBar("Add Survey",{finish()}) }) { innerPadding ->
                    Column (modifier = Modifier.padding(innerPadding)) {
                        SurveyForm(
                            questions = dummyQuestions,
                            uploadFileToServer = ::uploadFileToServer,
                            onSubmit = ::handleSubmit
                        )
//                        CTextField("Survey Name")
//                        var startintent= Intent(this@AddSurveyActivity, FormEditorActivity::class.java)
////                        CTextField("Survey Id") //Survey id is auto gen
////                        CTextField("Creation Time") // Creation time is auto gen
//                        Box {
//                            Row(
//                                modifier = Modifier.fillMaxWidth(),
//                                horizontalArrangement = Arrangement.Center
//                            ){
//                            OutlinedButton(onClick = { /*TODO*/ startActivity(startintent) }) {
//                                Text(
//                                    text = "Add Survey",
//                                    color = Color.Blue,
//                                    fontSize = 18.sp
//                                )
//                            }
//                            }
//                        }
                    }
                }
            }
        }
    }
}

//@Preview
//@Composable
//fun AddSurveyPreview() {
//    SmsmuicomposeTheme {
//        Scaffold(modifier = Modifier.fillMaxSize(), topBar = { TopBar("Add Survey",{null}) }) { innerPadding ->
//            Column (modifier = Modifier.padding(innerPadding)) {
//                CTextField("Survey Name")
////                CTextField("Survey Id") // Survey Id is auto generated by the backend
////                CTextField("Creation Time") // Creation time too is auto generated by the backend
//                Box {
//                    Row(
//                        modifier = Modifier.fillMaxWidth(),
//                        horizontalArrangement = Arrangement.Center
//                    ) {
//                        OutlinedButton(onClick = { /*TODO*/ }) {
//                            Text(
//                                text = "Add Survey",
//                                color = Color.Blue,
//                                fontSize = 18.sp
//                            )
//                        }
//                    }
//                }
//            }
//        }
//    }
//}

@Preview
@Composable
fun AddSurveyPreview() {
    SmsmuicomposeTheme {
        Scaffold(modifier = Modifier.fillMaxSize(), topBar = { TopBar("Add Survey",{null}) }) { innerPadding ->
            Column (modifier = Modifier.padding(innerPadding)) {
                SurveyForm(
                    questions = dummyQuestions,
                    uploadFileToServer = ::uploadFileToServer,
                    onSubmit = ::handleSubmit
                )
            }
        }
    }
}





sealed class Question(
    val id: String,
    val text: String,
    val type: QuestionType
) {
    class FileUpload(
        id: String,
        text: String,
        val allowedMimeTypes: List<String>,
        val maxFileSizeMB: Int
    ) : Question(id, text, QuestionType.FileUpload)

    class TextInput(
        id: String,
        text: String
    ) : Question(id, text, QuestionType.ShortText)

    class Rating(
        id: String,
        text: String,
        val maxStars: Int = 5
    ) : Question(id, text, QuestionType.ParagraphText)
}

val dummyQuestions = listOf(
    Question.FileUpload(
        id = "resume",
        text = "Upload your resume (PDF only)",
        allowedMimeTypes = listOf("application/pdf"),
        maxFileSizeMB = 5
    ),
    Question.TextInput(
        id = "full_name",
        text = "What is your full name?"
    ),
    Question.Rating(
        id = "experience",
        text = "How would you rate your interview experience?",
        maxStars = 5
    )
)


suspend fun uploadFileToServer(file: File): Boolean {
    delay(1000) // simulate network delay
    println("Uploaded: ${file.name}")
    return true
}

fun handleSubmit(answers: Map<String, Any?>) {
    answers.forEach { (questionId, answer) ->
        println("Answer to '$questionId': $answer")
    }
}
